### ISSUE TITLE
JEI only registering drops of pokemon without spawn biome

### ISSUE THREAD

**Issue by Stv13579** [Bletch1971/PixelmonInformation#14] opened 2020-04-12 04:45 UTC
Using JEI 4.1.5.0.293, Pixelmon 7.2.2, Pixelmon Information 7.2.0-0.3.4, and Forge 14.23.5.2847, JEI only displays the drops of pokemon that don't have a listed spawn biome, such as baby pokemon or fossils.

**Comment by Bletch1971** [comment] 2020-04-14 22:58
@Stv13579 Is this correct - you are only able to see the drops for pokemon without spawn biomes?

What shows when you select a pokemon that does have a spawn biome?

**Comment by Stv13579** [comment] 2020-04-15 00:19
Pokémon with spawn biomes simply aren’t registered-JEI only shows 130 entries for Pokémon drops instead of 800+. I can post a screenshot if that would help explain it.

**Comment by Bletch1971** [comment] 2020-04-15 12:15
Thanks, I think I understand the problem. I will try to take a look and fix.

**Comment by nuclear200** [comment] 2020-04-22 09:37
hmm maybe the issue i was going to report is a duplicate of this, but rather than an actual problem i was going to link an enormous error log (not a crash) referencing 
[11:10:20] [Client thread/INFO] [jei]: Building recipe registry...
[11:10:20] [Client thread/ERROR] [jei]: bletch.pixelmoninformation.jei.pokemon.PokemonEntry@2f64abad
Recipe Handler failed to create recipe wrapper
class mezz.jei.startup.ModRegistry$1
java.lang.NoSuchFieldError: biomes 

building up a 10k+ lines long log, with errors starting @ line 113
[latest.log](https://github.com/Bletch1971/PixelmonInformation/files/4515175/latest.log)

-same versions up here except forge (using 14.23.5.2854)-

**Comment by Stv13579** [comment] 2020-04-22 11:46
Yeah considering yours flat out says biomes I would bet that it is the same problem, and drops did work properly in 7.2.0 for me as well. Hopefully that log helps solve the problem, I didn’t think to post mine.

**Comment by Bletch1971** [comment] 2020-04-22 22:01
@Stv13579 @nuclear200 thanks for both - it looks like the pixolmon team have moved some settings around in 7.2.2 and is causing some problems for my mod.
I will take a look and see where the settings have moved to.

When you move settings like around in your code it should have been more than a 7.2.0 -> 7.2.2 version increase. 7.3.0 at least.

**Comment by Bletch1971** [comment] 2020-04-23 05:19
@Stv13579 @nuclear200 
Ok, I am unable to reproduce the error that you have both experienced.
How are you running this in minecraft
1. Single player
2. Dedicated server and one or more clients connecting to the dedicated server
3. Start a single player, then open to the LAN.

**Comment by Stv13579** [comment] 2020-04-23 06:00
@Bletch1971 
I’ve encountered this in both single player and on a dedicated server. I can confirm I posted the forge version I used, I can try the recommended one for pixelmon and see if that changes anything.

**Comment by Bletch1971** [comment] 2020-04-23 06:41
@Stv13579 @nuclear200 
Ok, I was not able to reproduce in my dev environment, but I was able to reproduce in my game environment.

What I have done is take the 0.3.4 code and just recompiled against pixelmon 7.2.2. This fixed it for me. Can you give it a try - I create 0.3.5 so the version will be different.

You can download the 0.3.5 beta file here - https://github.com/Bletch1971/PixelmonInformation/tree/master/beta/7.2

Let me know how you go

**Comment by nuclear200** [comment] 2020-04-23 06:46
just tried with forge 2838, just to be sure, and on the client this is happening during forge loading 6/7, when jei tries to load recipes;

**environment when this happens**
tested with: 
MultiMC 5 with forge [14.23.5.2838; 14.23.5.2847; 14.23.5.2854] --java jdk 1.8.0_231
Minecraft native launcher with forge [14.23.5.2838] --java: default jre that comes with the launcher

other mods installed are (just to be sure about version, maybe i've missed something):
JEI: jei_1.12.2-4.15.0.293
Pixelmon reforged: Pixelmon-1.12.2-7.2.2-universal

default generated config files

this only happens on clientside loading, server startup is flawless (even on forge 2854);
actual gameplay issues: [not yet checked on my side] should be all client behavior related

-> now i'll try with beta 0.3.5

**Comment by nuclear200** [comment] 2020-04-23 06:48
> -> now i'll try with beta 0.3.5

and it seems to be working (not spitting out errors at loading)

**Comment by Bletch1971** [comment] 2020-04-23 06:52
@Stv13579 @nuclear200 
So it appears as though the new compiled version works with 7.2.2, but does not work with 7.2.1 and 7.2.0. The issue appears for those versions.

Looks like I might have to close off 0.3.4 to only be for 7.2.0->7.2.1 and 0.3.5 will be for 7.2.2 and up.
Thing is the pixelmon code has not change in that area, so I am confused why this is causing my code grief.

**Comment by Bletch1971** [comment] 2020-04-23 07:35
@Stv13579 @nuclear200 
Ok, yes, there was a change to the code in 7.2.1 which carried through to 7.2.2.
They change the biomes property from an ArrayList to a Set, this is why it broke.

Now I know what broke I am hoping to fix it so it will work in all 7.2.x versions.

Thanks for your help.

**Comment by Bletch1971** [comment] 2020-04-23 12:53
@Stv13579 @nuclear200 
New version of the mod for 7.2.0 has been released - 0.3.5.
It contains the fix so it will work for 7.2.0, 7.2.1 and 7.2.2.

I also added the Infuser machine to JEI and it's recipes.

**Closed by Bletch1971** 2020-04-23 12:53 UTC
Labels: Fixed, bug
